/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Eurojackpot: typeof import('./src/components/Eurojackpot.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Landingpage: typeof import('./src/components/Landingpage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
